### ISSUE TITLE
搭建错误

### ISSUE THREAD

**Issue by odyf** [YianAndCode/typecho-in-docker#3]
你好，安装时候出现
常见错误：

错误：警告：无法修改标头信息 - 标头已经由（输出开始于 /var/www/html/install.php:202）在 /var/www/html/var/Typecho/Cookie.php on line 102 * 或*警告：无法修改标题信息 - 标题已由（输出开始于 /var/www/html/install.php:202）在 /var/www/html/install.php 第 559 行发送

解决方案：云数据库问题，在typecho/install.php 56行添加ob_start();

然后解决后出现
![image](https://user-images.githubusercontent.com/72725679/123205595-c9539300-d4ec-11eb-97e3-74f352a6028d.png)
**猜测PhP版本过高**

**Comment by YianAndCode** [comment]
建议直接使用 Typecho 仓库最新的 commit，Joyqi 上一次给 Typecho 打 release tag 已经是四年前了（然而他一直有在更新代码），很多在新版 PHP 的问题他都已经修复了，例如你提到的这个：[https://github.com/typecho/typecho/issues/1049](https://github.com/typecho/typecho/issues/1049)
